version: '3.7'

services:
  web:
    build: ./
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./:/usr/src/app/
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
