# Generated by Django 3.2 on 2024-02-22 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='We usualy order a model in a client and an admin part.', verbose_name='Sorting')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Show when an entry was created.', null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Show when an entry was updated', null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, help_text='This entry is visible or unvisible for a client part or admin part.', verbose_name='Public')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Delete status')),
                ('note', models.CharField(max_length=255, verbose_name='note')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='We usualy order a model in a client and an admin part.', verbose_name='Sorting')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Show when an entry was created.', null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Show when an entry was updated', null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, help_text='This entry is visible or unvisible for a client part or admin part.', verbose_name='Public')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Delete status')),
                ('name', models.CharField(max_length=255, verbose_name='blog name')),
                ('notes', models.ManyToManyField(to='user.Note', verbose_name='notes')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
