# Generated by Django 3.2 on 2024-09-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_blog_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
