# Generated by Django 3.2 on 2024-09-12 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='We usualy order a model in a client and an admin part.', verbose_name='Sorting')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Show when an entry was created.', null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Show when an entry was updated', null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, help_text='This entry is visible or unvisible for a client part or admin part.', verbose_name='Public')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Delete status')),
                ('title', models.CharField(max_length=255)),
                ('todo_status', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
