# Generated by Django 3.2 on 2024-09-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'Todo'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_status',
            field=models.PositiveIntegerField(choices=[(0, 'Not Finished'), (1, 'Done')], default=0, verbose_name='Todo status'),
        ),
    ]
