# Generated by Django 3.2 on 2024-09-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240912_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_status',
            field=models.PositiveIntegerField(choices=[(0, 'NOT_FINISHED'), (1, 'DONE')], default=0, verbose_name='Todo status'),
        ),
    ]
